name: Remix PR Build
on:
  pull_request:
    branches:
      - main
    paths:
      - apps/iq-flow/**
      - apps/margo/**
  workflow_dispatch:
jobs:
  pull:
    strategy:
      max-parallel: 2
      matrix:
        apps:
          [
            {
              title: 'IQ-Flow Remix',
              name: 'iq-flow-remixed',
              directory: 'apps/iq-flow',
            },
          ]
    runs-on: ubuntu-latest
    name: ${{ matrix.apps.title }} - PR Build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35.7.11
        with:
          files: |
            ${{ matrix.apps.directory }}
            packages

      - name: Setup Node 18
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: Add Yarn Globally
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm install --global yarn

      - name: Install packages
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn install

      - name: Bundle Size Check
        if: steps.changed-files.outputs.any_changed == 'true' && matrix.apps.name == 'iq-flow-remixed'
        run: |
          file_size=$(wc -c < ./apps/iq-flow/build/index.js)
          echo "File size is ${file_size} bytes"

      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Bundle Size Check For Main Branch
        if: steps.changed-files.outputs.any_changed == 'true' && matrix.apps.name == 'iq-flow-remixed'
        run: |
          file_size=$(wc -c < ./apps/iq-flow/build/index.js)
          echo "File size is ${file_size} bytes"

